<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My PHP Page</title>
</head>
<body>
    <h1>Welcome!</h1>

    <?php
        echo "<p>This is generated by PHP!</p>";
    ?>

</body>
</html>